### ISSUE TITLE
Need 1 or two servers ?

### ISSUE THREAD

**Issue by divancorp** [mehnomy/FBCTF-Ubuntu-Setup#2]
Hello 
Do I need one server for Admin and one server for users access? Would you please elaborate server configuration and set up process for users to use.

**Comment by mehnomy** [comment]
Hello @divancorp 

This guide provides you the instructions to setup the Facebook Capture the Flag Environment which allows you to keep track of teams scores, and track what flags have been completed or being challenged. The actual challenges themselves should be set up on a different server(s) as you wouldn't want contestants trying to hack into the server which is hosting the platform.

Admin and Users both log onto the same platform:
- Admin users see the Admin Panel 
- Normal users (contestants) log in and only see the challenges (world map).
 - Please play around with it yourself to see what each user has access to.

Kind Regards,
Byron Fisher

**Comment by divancorp** [comment]
Thank you
